### PR TITLE
Packaging files for PyPI release 3.5.0

### PR DESCRIPTION
**Pull request by vlasovskikh**
Please review my changes to setup.py from 3.5.0b1.

### CODE REVIEW

**Comment by ambv** [comment]
Perfect. Thank you for doing this. Can you rename `prototyping/` to `src/`?

**Comment by vlasovskikh** [comment]
Sure. Should we move LICENSE, MANIFEST.in and setup.py to the top-level directory?

**Comment by ambv** [comment]
Yes, please. You can also move all other files to `drafts/` so it's more obvious this is kept for historical reasons.

**Comment by ambv** [comment]
(I meant the .rst files)

**Comment by vlasovskikh** [comment]
Here it is.

**Comment by ambv** [comment]
Thanks again!

**Pull request merged**
